### ISSUE TITLE
UnsupportedClassVersionError

### ISSUE THREAD

**Issue by sherppard** [bit4woo/GUI_Burp_Extender_ReSign#3]
加入扩展的时候，提示了这个异常，请问需要更新到什么版本？
java.lang.UnsupportedClassVersionError: burp/BurpExtender : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at burp.hie.a(Unknown Source)
	at burp.hie.<init>(Unknown Source)
	at burp.sxf.a(Unknown Source)
	at burp.r5h.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
The extension could not be loaded because it requires a later version of Java. To use this extension you will need to start Burp with the required or later Java version.

**Comment by bit4woo** [comment]
你好，我是在Java 1.8上写的这个插件。错误应该是Java版本不兼容导致的

**Comment by sherppard** [comment]
谢谢回复。之前已经解决了。
